In [3]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 19.3 MB/s eta 0:00:00 MB/s eta 0:00:0102

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip


In [4]:
import numpy as np


In [12]:
#Create Arrays

In [5]:
#np.arrays() it is used to create array from existing list,tuple or set
#suppose we have an array 
#Convert the list x into an array
x = [10,21,31,61]
x_array = np.array(x)
print(x_array)

y = [10,20,40,50]
y_array = np.array(y)
print(y)

[10 21 31 61]
[10, 20, 40, 50]


In [26]:
#np.arrange() It is used to create array in numbers in range

#Create an array of numbers from 1 to 20
nums = np.arange(1,20)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [30]:
#Create an array of numbers from 3 to 99 in step 6
#syntax: np.arange(start_value, ending_value,step)
nums2 = np.arange(3,99,6)
nums2

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93])

In [7]:
num3 = np.arange(1,20,2)
num3 = 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
n33 = num3*2
n33

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38])

In [11]:
array1212 = np.array([1,2,3,4,5,6,7,8,9])
print(array1212)

[1 2 3 4 5 6 7 8 9]


In [14]:
# create an array of numbers from 3 to 99 in step 7
task = np.arange(3,100,6)
task

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99])

In [15]:
#Create an array with zeros.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
#Create with ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
#np.full(how mny items,. which item)
np.full(5,1)

array([1, 1, 1, 1, 1])

In [19]:
#Create 2D array
x= list("ABCDEFGHI")
x


['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [21]:
y =x[::-1]
y

['I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [29]:
demo = np.array([x,y])
demo

array([['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
       ['I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']], dtype='<U1')

In [30]:
#Properties of Array

#dimension: it its the number of dimensions, ndim()
#shape number of row and column if form of tuple ()
#size product of row and column of an array
np.ndim(demo)

2

In [37]:
#find the shape of array 'nums'

print(np.shape(demo))

(2, 9)


In [44]:
#size()
#returns the product of row and column
# or demo.size
print(np.size(demo))

18


In [47]:
#dtype
demo.dtype

n33.dtype

dtype('int64')

In [ ]:
#Reshapping of an array
#reshaping of an array is the process of changinf row and column of array so that the original size of an array should not change


In [48]:
x

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [49]:
y

['I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [51]:
test = np.array([x,y])
test

array([['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
       ['I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']], dtype='<U1')

In [53]:
test.size

18

In [54]:
test.reshape(6,3)

array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['G', 'H', 'I'],
       ['I', 'H', 'G'],
       ['F', 'E', 'D'],
       ['C', 'B', 'A']], dtype='<U1')

In [55]:
#Transpose
#Flatten

demo.transpose()

array([['A', 'I'],
       ['B', 'H'],
       ['C', 'G'],
       ['D', 'F'],
       ['E', 'E'],
       ['F', 'D'],
       ['G', 'C'],
       ['H', 'B'],
       ['I', 'A']], dtype='<U1')

In [56]:
np.transpose(demo)

array([['A', 'I'],
       ['B', 'H'],
       ['C', 'G'],
       ['D', 'F'],
       ['E', 'E'],
       ['F', 'D'],
       ['G', 'C'],
       ['H', 'B'],
       ['I', 'A']], dtype='<U1')

In [58]:
#flatten() COnverts 2D array in 1D array

demo.flatten

<function ndarray.flatten(order='C')>

In [59]:
#Maths operatiion in Numpy Array.


In [60]:
x = np.array([10,21,31])
y = np.array([3,4,5])
x+y

array([13, 25, 36])

In [61]:
t = np.array([x,y])
t

array([[10, 21, 31],
       [ 3,  4,  5]])

In [62]:
x+t

array([[20, 42, 62],
       [13, 25, 36]])

In [63]:
print(x-y)
print(x+y)
print(x/y)
print(x%y)

[ 7 17 26]
[13 25 36]
[3.33333333 5.25       6.2       ]
[1 1 1]


In [64]:
#scalar Operartions

print(x+7)

[17 28 38]


In [70]:
t = np.array([10,21,31])
t2 = np.sqrt(t)
t3 = np.square(t)
print(t2)
t3
print(np.power(t,3))

[3.16227766 4.58257569 5.56776436]
[ 1000  9261 29791]


In [72]:
#Aggerated Functions
x = list(range(4,41,4))
x

[4, 8, 12, 16, 20, 24, 28, 32, 36, 40]

In [78]:
ary = np.array([list(range(4,41,4)), list(range(5,51,5)), list(range(6,61,6)), list(range(7,71,7))])
ary

array([[ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70]])

In [80]:
ary.sum() #DFind total of all items in array

np.int64(1210)

In [81]:
ary.sum(axis =1) #Find sum of all items row wise

array([220, 275, 330, 385])

In [82]:
ary.sum(axis=0) #sum column wise

array([ 22,  44,  66,  88, 110, 132, 154, 176, 198, 220])

In [83]:
#Mean() Find mean values of all item in array
ary.mean()


np.float64(30.25)

In [84]:
ary.mean(axis=1) #Find mean row wise

array([22. , 27.5, 33. , 38.5])

In [85]:
ary.mean(axis=0) # Mean columnwise

array([ 5.5, 11. , 16.5, 22. , 27.5, 33. , 38.5, 44. , 49.5, 55. ])

In [86]:
#min()
ary.min()

np.int64(4)

In [87]:
#max
ary.max()

np.int64(70)

In [88]:
ary.std()

np.float64(17.25362280797862)

In [93]:
#indexing and slicing

#way of finding items from a array
x= np.array(list("KATHMANDU"))
x


array(['K', 'A', 'T', 'H', 'M', 'A', 'N', 'D', 'U'], dtype='<U1')

In [94]:
x[-1]

np.str_('U')

In [ ]:
#slicing, geting portion of array


In [96]:
#get the slice of array x from index 1 to 5

x1 = x[:6]
x1

array(['K', 'A', 'T', 'H', 'M', 'A'], dtype='<U1')

In [99]:
tes = np.array(list("kathmandu"))
tes

array(['k', 'a', 't', 'h', 'm', 'a', 'n', 'd', 'u'], dtype='<U1')

In [100]:
#reverse slicing
x[-1:-4:-1]

array(['U', 'D', 'N'], dtype='<U1')

In [101]:
x[::-1]

array(['U', 'D', 'N', 'A', 'M', 'H', 'T', 'A', 'K'], dtype='<U1')

In [102]:
x

array(['K', 'A', 'T', 'H', 'M', 'A', 'N', 'D', 'U'], dtype='<U1')

In [107]:
y = x[::-1]
y

array(['U', 'D', 'N', 'A', 'M', 'H', 'T', 'A', 'K'], dtype='<U1')

In [111]:
test1 = np.array([x,y,x,y,x,y,x,y,x,y])
test1.shape
test1

array([['K', 'A', 'T', 'H', 'M', 'A', 'N', 'D', 'U'],
       ['U', 'D', 'N', 'A', 'M', 'H', 'T', 'A', 'K'],
       ['K', 'A', 'T', 'H', 'M', 'A', 'N', 'D', 'U'],
       ['U', 'D', 'N', 'A', 'M', 'H', 'T', 'A', 'K'],
       ['K', 'A', 'T', 'H', 'M', 'A', 'N', 'D', 'U'],
       ['U', 'D', 'N', 'A', 'M', 'H', 'T', 'A', 'K'],
       ['K', 'A', 'T', 'H', 'M', 'A', 'N', 'D', 'U'],
       ['U', 'D', 'N', 'A', 'M', 'H', 'T', 'A', 'K'],
       ['K', 'A', 'T', 'H', 'M', 'A', 'N', 'D', 'U'],
       ['U', 'D', 'N', 'A', 'M', 'H', 'T', 'A', 'K']], dtype='<U1')

In [109]:
#rows =10
#column =9

#get all the data from row 0
test1[0]

array(['K', 'A', 'T', 'H', 'M', 'A', 'N', 'D', 'U'], dtype='<U1')

In [112]:
test1[1]

array(['U', 'D', 'N', 'A', 'M', 'H', 'T', 'A', 'K'], dtype='<U1')

In [114]:
#give me all data from column 0
test1[:,0]

array(['K', 'U', 'K', 'U', 'K', 'U', 'K', 'U', 'K', 'U'], dtype='<U1')

In [115]:
#get all datas from row and col0,1,2

test1[:,0:3]

array([['K', 'A', 'T'],
       ['U', 'D', 'N'],
       ['K', 'A', 'T'],
       ['U', 'D', 'N'],
       ['K', 'A', 'T'],
       ['U', 'D', 'N'],
       ['K', 'A', 'T'],
       ['U', 'D', 'N'],
       ['K', 'A', 'T'],
       ['U', 'D', 'N']], dtype='<U1')

In [118]:
#get all data from test1 all rows and column 1,4 ,8
test1[:,[1,4,7]]

array([['A', 'M', 'D'],
       ['D', 'M', 'A'],
       ['A', 'M', 'D'],
       ['D', 'M', 'A'],
       ['A', 'M', 'D'],
       ['D', 'M', 'A'],
       ['A', 'M', 'D'],
       ['D', 'M', 'A'],
       ['A', 'M', 'D'],
       ['D', 'M', 'A']], dtype='<U1')

In [120]:
test1[1:6,1:5]

array([['D', 'N', 'A', 'M'],
       ['A', 'T', 'H', 'M'],
       ['D', 'N', 'A', 'M'],
       ['A', 'T', 'H', 'M'],
       ['D', 'N', 'A', 'M']], dtype='<U1')

In [123]:
#get row index 1,3,4 ,6 and col 0,3,5,6

test1[[1,2,4,6],[0,3,5,6]]

array(['U', 'H', 'A', 'N'], dtype='<U1')

In [126]:
a = ['x','y','z']
b = ['m','n','o']
c= ['k','l','m']
t = np.array([a,b,a,c,b])
t

array([['x', 'y', 'z'],
       ['m', 'n', 'o'],
       ['x', 'y', 'z'],
       ['k', 'l', 'm'],
       ['m', 'n', 'o']], dtype='<U1')

In [130]:
#get data from row 1,3,4 and col 0,2
t[[1,3],[0,2]]


array(['m', 'm'], dtype='<U1')

In [132]:
#Stacking of arrays

x = list([5,6,10,21,13])
y = x[::-1]

